### PR TITLE
Add Kyle Kloster's authorship

### PR DESCRIPTION
**Pull request by kkloste**
I am no longer working at NC State, but all of my contributions were completed while at NC State,
so I believe listing my affiliation as "NC State" is appropriate in this case.

### CODE REVIEW

**Comment by kkloste** [comment]
I feel silly, but after making this pull request I thought more about it, and I've decided I just won't have time to contribute to preparing a manuscript.

I am disappointed, because the work is really cool and I would have loved to be a part of it, but I won't be able to uphold the responsibilities of a co-author.
Thanks for tagging me for the opportunity, @dhimmel !
Excited to see the finished product.

**Comment by dhimmel** [comment]
> I am no longer working at NC State, but all of my contributions were completed while at NC State, so I believe listing my affiliation as "NC State" is appropriate in this case.

I agree you should list NC State. Also okay to list your current affiliation.

> I've decided I just won't have time to contribute to preparing a manuscript.

I think this is perhaps the wrong decision as we are grateful for your contributions. I don't envision the remaining steps taking too much time. Primarily I think you'd want to read through @zietzm's formulas and make sure they are described sufficiently.

Anyways, if you'd like to hold off on being an author, then let us know. If you'd like us to merge this and proceed with authorship, then great. No need to decide now if your availability is still TBD... but I don't think the remaining steps on your end will be too burdensome.

**Comment by kkloste** [comment]
Thanks for your comments, @dhimmel . I start a new job in two weeks, and I'll better understand my availability then. If it's ok, I'll hold off until then? I would be happy to contribute with proofreading and looking over @zietzm 's formulas and description, once I can confirm I'll have the time to do so.

**Comment by dhimmel** [comment]
Sounds good. Will keep this PR open until we get the final word from you. Best of luck.

**Comment by zietzm** [comment]
@kkloste, the [section of the manuscript on the analytical approximation](https://greenelab.github.io/xswap-manuscript/#approx-prior-supp) should be ready for your review, if/when you get the chance to take a look at it. It is about one page printed, and shouldn't take too long to go through.

Would really love to get your feedback on it (and merge this PR if possible), as your work was really instrumental in finding the current approximation.

**Comment by kkloste** [comment]
I can definitely make time to read over this and help with edits early this week.
I think I can make a first pass tonight.
With this in mind, I'll merge this PR and proceed with authorship.

I really appreciate everyone encouraging me on this!

**Comment by cgreene** [comment]
Woo! 🎊

**Pull request merged**
